#!/usr/bin/env python
import os
import subprocess

import twosheds


def sh(command):
    """Run a command in the shell and capture the output."""
    return subprocess.check_output(command, shell=True)


HUMAN_ALIASES = {
    'copy': 'cp',
    # ask before overriding files
    'cp': 'cp -i',
    'edit': '$EDITOR',
    # sort variables
    'env': 'env | xargs -0 | sort',
    'del': 'rm',
    'delete': 'rm',
    'goto': 'cd',
    # color output
    'grep': 'grep --color=auto',
    'list': 'ls',
    # color output
    'ls': 'ls -G',
    'move': 'mv',
    'now': 'date',
    'whereami': 'pwd',
    'unixtime': 'date +$%s',
}

UTILITY_ALIASES = {
    # more intuitive xargs
    'args': 'xargs -0',
    # grep recursively. show line numbers and one line of context on either side
    'f': 'grep -rn -C 1',
    # find name
    'fn': 'find . -name',
     # Remove all local merged branches
    'gitclean': 'git branch --merged | grep -v ^\* | sed "s/^ *//" | xargs -n 1 git accept',
     # Remove all remote merged branches
    'gitcleanremote': 'git branch --merged | grep -v ^\* | sed "s/^ *//" | xargs -n 1 git accept',
    # list filenames by relative path
    'lr': 'find . -type f | sed "s#^./##',
    # check connection speed
    'pingme': 'ping google.com',
    'vimrc': '$EDITOR ~/.vimrc',
}

SHORT_ALIASES = {
    '..': 'cd ..',
    '...': 'cd ...',
    'c': 'cd',
    'e': '$EDITOR',
    'g': 'git',
    'gs': "git status",
    'l': 'ls -G',
    # show hidden files
    'la': 'ls -aG',
    # show file metadata and symlinks pointers
    'll': 'ls -lG',
    'v': '$EDITOR',
}

def get_aliases():
    return dict(HUMAN_ALIASES.items()
                + UTILITY_ALIASES.items()
                + SHORT_ALIASES.items())

os.environ['EDITOR'] = "vim"
os.environ['HOST'] = "$(uname -n)"
os.environ.setdefault('UNAME', "$(uname)")

PATH = ["$HOME/local/bin",
        "$HOME/bin",
        "/usr/local/bin",
        "/usr/bin",
        "/usr/sbin",
        "/usr/X11R6/bin",
        "/bin",
        "/sbin",
        ]
os.environ['PATH'] = ":".join(PATH)
# NOTE: for some reason $HOME does not get expanded
os.environ['PYTHONSTARTUP'] = os.environ['HOME'] + "/.pythonrc.py"
os.environ['VISUAL'] = os.environ['EDITOR']


class MyShell(twosheds.Shell):
    last_ls = ""
    last_gs = ""

    @property
    def git_branch(self):
        """The current git branch."""
        try:
            return sh("git symbolic-ref --short HEAD 2> /dev/null").strip()
        except subprocess.CalledProcessError:
            return None

    @property
    def working_directory(self):
        """The current working directory."""
        return os.getcwd().replace(os.environ["HOME"], "~")

    @property
    def prompt(self):
        working_directory = self.working_directory
        branch = self.git_branch
        if branch is not None:
            return "%s(%s) " % (working_directory, branch)
        else:
            return working_directory + " "

    def auto_gs(self):
        """Automatically run ``git status`` if the output changes."""
        try:
            gs = sh("git status 2> /dev/null")
        except subprocess.CalledProcessError:
            pass
        else:
            if gs != self.last_gs:
                self.last_gs = gs
                self.eval("git status -s")

    def auto_ls(self):
        """Automatically run ``ls`` if the output changes."""
        ls = sh("ls")
        if ls != self.last_ls:
            self.last_ls = ls
            # NOTE: Not sure this really belongs here
            self.eval("clear")
            self.eval("ls")

    def read(self):
        self.auto_ls()
        self.auto_gs()
        return super(MyShell, self).read()

shell = MyShell(aliases=get_aliases(), echo=True, exclude=[r'.*.pyc'])
shell.interact("Hello!")
