#!/usr/bin/env python
import os
from subprocess import call, check_output

from twosheds import Shell
from twosheds.completer import Completer
from twosheds.history import History

ALIASES = {
    'cp': 'cp -i',
    # sort variables
    'env': 'env | xargs -0 | sort',
    # color output
    'ls': 'ls -G',
    # color output
    'grep': 'grep --color=auto',
}

HUMAN_ALIASES = {
    'copy': 'cp',
    'del': 'rm',
    'delete': 'rm',
    'goto': 'cd',
    'list': 'ls',
    'move': 'mv',
    'now': 'date',
    'whereami': 'pwd',
    'unixtime': 'date +$%s',
}

UTILITY_ALIASES = {
    # more intuitive xargs
    'args': 'xargs -0',
    # grep recursively. show line numbers and one line of context on either side
    'f': 'grep -rn -C 1',
    # find name
    'fn': 'find . -name',
    # list filenames by relative path
    'lr': 'find . -type f | sed "s#^./##',
    # tell me what OS this is
    'os': 'uname -srm',
    # check connection speed
    'pingme': 'ping google.com',
}

SHORT_ALIASES = {
    '..': 'cd ..',
    '...': 'cd ...',
    'c': 'cd',
    'e': '$EDITOR',
    'l': 'ls -G',
    # show hidden files
    'la': 'ls -aG',
    # show file metadata and symlinks pointers
    'll': 'ls -lG',
    'v': '$EDITOR',
}

def get_aliases():
    return dict(ALIASES.items()
                + HUMAN_ALIASES.items()
                + UTILITY_ALIASES.items()
                + SHORT_ALIASES.items())

PATH = ["/Users/ceasarbautista/local/bin",
        "/Users/ceasarbautista/local/bin/icon/bin",
        "/Users/ceasarbautista/bin",
        "/usr/local/bin",
        "/usr/bin",
        "/usr/sbin",
        "/usr/X11R6/bin",
        "/bin",
        "/sbin",
        "/Users/ceasarbautista/Library/Haskell/ghc-7.4.1/lib/ghc-mod-1.11.0/bin",
        ]

os.environ['PATH'] = ":".join(PATH)


class MyShell(Shell):
    last = ""

    @property
    def prompt(self):
        pwd = check_output("pwd", shell=True)
        return (pwd.strip() + " ").replace(os.environ["HOME"], "~")

    def eval(self, line):
        super(MyShell, self).eval(line)
        ls = check_output("ls", shell=True)
        if ls != self.last:
            self.last = ls
            if "ls" not in line:
                call("ls -G", shell=True)

shell = History(Completer(MyShell(aliases=get_aliases()), exclude=[r'.*.pyc']))
shell.interact("Hello Ceasar!")
